problems = `
-----s--s-eb-ev-b--
-c-c-s-tct---cs--c-
tc-s-d-re-srces-s--
--brc----dc--r-sr-r
-r---s--rtd-bbb-c--
cs--cs----s---csc--
bs----s--d--c--s--c
ducd-uc-d-ub-dubd-u
test-est--erte-rte-
b-rbbr---k---ds-tds
c---rc-b-uc-r-s--sc
s--cbs---ds---d--bs
c--sc---s-e--ses-s-
rr-dr----d----rr-dr
ssetseteeessssettse
d--sd-d-sdd--s---s-
bcs-d-ss-e--sudtc--
`.trim().split('\n')